### ISSUE TITLE
Not able to alter Topics (Increasing partitions)

### ISSUE THREAD

**Issue by ritxos** [birdayz/kaf#101]
Hi I can't figure out a way to increase partitions. if there is no existing way, i think it will be a good add on.

**Comment by birdayz** [comment]
we can add it, it's in the AdminAPI and also available via Sarama.

i propose to add `kaf topic update` - with the -p / --partitions flag.

Example:

```
kaf topic update my-topic -p 30
```

Things to consider:
- Partition to replica assignments have to be provided as well: it's a int32->int32 mapping
- Use -p or something else? 

Maybe i'll get a shot at this in the evening.

**Comment by birdayz** [comment]
I've implemented this, you can get it with the newest release: https://github.com/birdayz/kaf/releases/tag/v0.1.34

usage:
```
kaf topic update abc -p 21 --partition-assignments '[[1],[1]]'
```

update topic abc to have 21 partitions. assign both new partitions to broker '1'. partition assignments is optional though, the following will work as well:
```
kaf topic update abc -p 21
```

**Comment by ritxos** [comment]
Thanks @birdayz
