### ISSUE TITLE
admin.AlterPartitionReassignments undefined (type sarama.ClusterAdmin has no field or method AlterPartitionReassignments)

### ISSUE THREAD

**Issue by d-i-bondarenko** [birdayz/kaf#124]
I have this issue during installation. Using go 1.15.3:

```
> go get github.com/birdayz/kaf/cmd/kaf
# github.com/birdayz/kaf/cmd/kaf
go/src/github.com/birdayz/kaf/cmd/kaf/topic.go:119:16: admin.AlterPartitionReassignments undefined (type sarama.ClusterAdmin has no field or method AlterPartitionReassignments)
```

What's going wrong?

**Comment by birdayz** [comment]
i update the vendor folder and go.sum. can you try again? it works for me.

**Comment by d-i-bondarenko** [comment]
> i updated the vendor folder and go.sum. can you try again? it works for me.

@birdayz still the same. I've tried to clean up go caches, but this issue continues.

**Comment by d-i-bondarenko** [comment]
`go get -u github.com/birdayz/kaf/cmd/kaf` works for me.
