### ISSUE TITLE
Support for Kafka 2.7.0

### ISSUE THREAD

**Issue by andreasevers** [birdayz/kaf#162]
When trying to execute `kaf group commit my-consumer-group -t my.topic -o 0 --all-partitions`
I received the following error:
> Failed to commit offset: kafka server: The provider group protocol type is incompatible with the other members.

Turns out my Kafka version is 2.7.0, and `kaf` seems to support up to 2.6.0.

Would this be the cause of the error, and if so, can 2.7.0 be supported as well?

Cheers,
Andreas

**Comment by birdayz** [comment]
First stop all consumers of this group

**Comment by andreasevers** [comment]
Oh boy thanks for that @birdayz 

Do I leave this issue open for 2.7.0 support?

**Comment by birdayz** [comment]
There's no problem with 2.7.0 as far as i know - i'm using 2.8.0 myself with no problems.
