### ISSUE TITLE
Support for arm64 and apple m1 silicon

### ISSUE THREAD

**Issue by WojtylaCZ** [birdayz/kaf#170]
Hi there. Thanks for this great lib. Can we add/allow the arm64 native support? 

```
birdayz/kaf crit platform darwin/arm64 is not supported.
```

I just tested it on my M1 laptop it works fine.

Just to add  `darwin/arm64) found=0 ;;` [to here](https://github.com/birdayz/kaf/blob/master/godownloader.sh#L67)

**Comment by birdayz** [comment]
i added darwin/arm64 - can you try the v0.1.44 release?

**Comment by birdayz** [comment]
i forgot to update godownloader - did that now. i'd appreciate a re-test :)
