### ISSUE TITLE
Homebrew recipe

### ISSUE THREAD

**Issue by SanketDG** [birdayz/kaf#190]
So that I can:

```
brew install kaf
```

**Comment by eshepelyuk** [comment]
Please please :)

It is not only for Mac, brew works on Linux and via Ubuntu + WSL on Windows. In our company of mostly windows laptops we use brew as a main installation method for CLI tools.

**Comment by birdayz** [comment]
it looks like goreleaser can integrate with homebrew:
https://goreleaser.com/customization/homebrew/

i understand, that a homebrew tap can be hosted in a git repository, so it could be here. i am happy to accept a PR implementing that. since i can't test it myself without OSX, i can't do it myself even if i wanted to.

**Comment by birdayz** [comment]
okay; i just gave it a shot: https://github.com/birdayz/homebrew-kaf

can you try it out?
```
brew tap birdayz/kaf
```

and then i guess
```
brew cask install kaf
```

can somebody try?

**Comment by eshepelyuk** [comment]
@birdayz brew is not for macs, you can use it on plain ubuntu, on virtual ubuntu on windows/wsl2 etc. So you can try it yourself.

Sure I wil give it also give it a try as soon as i be near my laptop.

**Comment by eshepelyuk** [comment]
Hello @birdayz - everything _just works_ !

Here's what I did, using WSL2 based Ubuntu distribution. ( i.e. i'm using windows 10)

1. `brew tap birdayz/kaf`
1. `brew install kaf`

Then
```
$ which kaf
/home/linuxbrew/.linuxbrew/bin/kaf
$ kaf --version
kaf version 0.1.47 (daa85b9658f4ac3706d8a8965f4ab87c52f01fd8)
```

Got some questions though
1. Are you going to provide a PR into `Homebrew` repo ?
1. Are you gonna update installation docs accordingly ?

**Comment by birdayz** [comment]
1) homebrew-core does not accept binary formulas. it has to be built from source. goreleaser does binary only
1.1) homebrew-cask afaik does accept it, but i don't know about the requirements/process/etc. it's not important to me. i guess it's not too important to upstream it, people can just use the tap birdayz/kaf.
2) done
