### ISSUE TITLE
Set exit code 1 when a command errors out

### ISSUE THREAD

**Issue by joeirimpan** [birdayz/kaf#208]
@birdayz Thanks for this easy-to-use kafka cli.

Is there a specific reason we are not setting `exit 1` when a command like [`kaf topic create test-topic`](https://github.com/birdayz/kaf/blob/master/cmd/kaf/topic.go#L282) fails?

**Comment by joeirimpan** [comment]
@birdayz i am sure you are busy but, bumping this up to hear your thoughts. Thanks again!

**Comment by birdayz** [comment]
sorry for the late response. this is a bug.
