### ISSUE TITLE
Cluster config flags without the config file

### ISSUE THREAD

**Issue by LinkedList** [birdayz/kaf#225]
Hi there, 

is it possible to use the commands without the config file for a cluster? 

I would like to dynamically use kaf in our CI for some housecleaning work and would like to avoid creating the config file manually.

e.g. use it in a similar fashion to this:

```
kaf groups --broker <broker-here> --username <username-here> --password <password-here> ... other needed configs follow
```

**Comment by jackcipher** [comment]
Hi there.

Kafka supports almost seven authentication mechanisms, which makes it difficult to cover all authentication methods using just command parameters. If you need to frequently change the configuration, you might want to consider using the -c flag to select a different configuration.

**Comment by LinkedList** [comment]
Makes sense, thank you for looking into this 👍
