### ISSUE TITLE
groups: reset/change offset

### ISSUE THREAD

**Issue by birdayz** [birdayz/kaf#25]

**Comment by birdayz** [comment]
ref: https://gist.github.com/marwei/cd40657c481f94ebe273ecc16601674b

**Comment by StephenSorriaux** [comment]
It would be a great feature :)

**Comment by birdayz** [comment]
could be implemented with https://github.com/Shopify/sarama/pull/932

**Comment by mbonnefoy** [comment]
Hey @birdayz ,

First, thanks for the project, it's a great tool.

Is reset / change offset that is still planned to be added?

Cheers,
Matthieu

**Comment by birdayz** [comment]
this has been implemented already!

```
kaf group commit <group name> -t <topic name> -p 0 -o 5000
kaf group commit <group name> -t <topic name> -p 0 -o 2020-11-17T20:00:00Z
kaf group commit <group name> -t <topic name> --all-partitions -o 2020-11-17T20:00:00Z
```

group must be empty (scale to 0 your consumers) when calling the command.

**Comment by mbonnefoy** [comment]
Thanks!
