### ISSUE TITLE
panic: runtime error: makeslice: cap out of range

### ISSUE THREAD

**Issue by smlgbl** [birdayz/kaf#65]
I regularly encounter the following error message for groups consuming topics with 360 partitions and more:

> $ kaf group describe consumer-group.prod
> Group ID:        offer-upgrade-processor.prod
> State:           Stable
> Protocol:        stream
> Protocol Type:   consumer
> Offsets:         
>  topic1:
>    Partition  Group Offset  High Watermark  Lag  
>    ---------  ------------  --------------  ---  
>    0          48321         48321           0    
>    1          48155         48155           0    
>    2          48113         48113           0    
>    3          48556         48556           0
>  ...
>   topic2:
>     Partition  Group Offset  High Watermark  Lag   
>     ---------  ------------  --------------  ---   
>     0          1129687383    1129687722      339   
>     1          1129936247    1129936511      264   
>    2          1128154286    1128154637      351
> ...
> Members:
>  consumer-group.prod-54418c37-2b3e-4c6a-825b-1b935ff775ce-StreamThread-1-consumer:
>    Host:  /10.114.0.12
>    Assignments:
>      Topic              Partitions                                              
>      -----              ----------                                              
>      topic1  [36 60 84 108 132 156 180 204 228 252 276 300 324 348]  
>      topic2   [36 60 84 108 132 156 180 204 228 252 276 300 324 348]  
>    Metadata:  AAAAAwAAAANUQYw3Kz5MaoJbG5Nf93XOAAAAAAAAAAAAAAAA
>  consumer-group.prod-54418c37-2b3e-4c6a-825b-1b935ff775ce-StreamThread-3-consumer:
>    Host:  /10.114.0.12
>    Assignments:
>      Topic              Partitions                                              
>      -----              ----------                                              
>      topic1   [33 57 81 105 129 153 177 201 225 249 273 297 321 345]  
>      topic2  [33 57 81 105 129 153 177 201 225 249 273 297 321 345]  
>
> panic: runtime error: makeslice: cap out of range
> 
> goroutine 1 [running]:
> github.com/birdayz/kaf.(*SubscriptionInfo).Decode(0xc000511808, 0x16dfe80, 0xc00018e0c0, 0x11, 0x11)
	/home/j0e/projects/kaf/subscription_info.go:29 +0x11a
> main.tryDecodeUserData(0xc0001d4088, 0x6, 0xc0003a618c, 0x24, 0x5733, 0x0, 0x0, 0x4e, 0x0)
> 	/home/j0e/projects/kaf/cmd/kaf/group.go:309 +0x150
main.glob..func10(0x1a9dd40, 0xc0000a34a0, 0x1, 0x1)
> 	/home/j0e/projects/kaf/cmd/kaf/group.go:213 +0x115f
github.com/spf13/cobra.(*Command).execute(0x1a9dd40, 0xc0000a3460, 0x1, 0x1, 0x1a9dd40, 0xc0000a3460)
> 	/home/j0e/gopath/pkg/mod/github.com/spf13/cobra@v0.0.5/command.go:830 +0x2ae
github.com/spf13/cobra.(*Command).ExecuteC(0x1a9dfc0, 0xa, 0xc0000bdf88, 0x100552f)
> 	/home/j0e/gopath/pkg/mod/github.com/spf13/cobra@v0.0.5/command.go:914 +0x2fc
github.com/spf13/cobra.(*Command).Execute(...)
> 	/home/j0e/gopath/pkg/mod/github.com/spf13/cobra@v0.0.5/command.go:864
main.main()
> 	/home/j0e/projects/kaf/cmd/kaf/kaf.go:63 +0x32

**Comment by birdayz** [comment]
thanks for reporting. i think i've found the cause; in some case my code tried to make a slice with size 0.

can you try v0.1.22 please?

**Comment by smlgbl** [comment]
@birdayz That is much better! Thank you very much. It's also a lot faster, it seems...

**Comment by birdayz** [comment]
Yeah that's fix from the last release where i updated the code to fetch consumer group offsets.
